### ISSUE TITLE
Default address in used

### ISSUE THREAD

**Issue by hnngo** [fc5y/email-service#2]
Currently, addres 3000 is already in used for DB Gateway (we deployed different services in the same server), please change to another address port.

![image](https://user-images.githubusercontent.com/43344276/120085469-ec1ba300-c10a-11eb-80b8-d2b3a1ff2237.png)

List of current address:
```
API v1: 4000
API v2: 9000
DB Gateway: 3000
```

**Comment by a2dalek** [comment]
em vừa tạo một pull request để sửa, các anh review cho em với ạ
